name: Generate Snake

on:
  # Executa automaticamente a cada 24 horas
  schedule:
    - cron: "0 0 * * *"
  
  # Permite rodar manualmente na aba "Actions"
  workflow_dispatch:
  
  # Executa sempre que houver um push nabranch main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Gera os arquivos da cobrinha
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#6796e3,#38618c,#0c2d48

      # Salva os arquivos gerados em uma branch específica (output)
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
